#spring:
#  profiles:
#    active: dev
spring:
  application:
    name: mall-gateway
  redis:
    host: vm.com
    port: 6389
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
          # 转发规则 http://Gateway_HOST:Gateway_PORT/serviceId/**(path)

      routes:
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**

        - id: mall-index
          uri: lb://mall-web
          predicates:
            - Host=www.gmall.com,search.gmall.com, item.gmall.com, passport.gmall.com, cart.gmall.com, order.gmall.com, payment.gmall.com, seckill.gmall.com

        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/user/**

        - id: mall-cart
          uri: lb://mall-cart
          predicates:
            - Path=/cart/**

        - id: mall-order
          uri: lb://mall-order
          predicates:
            - Path=/order/**

        - id: mall-payment
          uri: lb://mall-payment
          predicates:
            - Path=/payment/**

server:
  port: 80
