#spring:
#  profiles:
#    active: dev
spring:
  application:
    name: mall-gateway
  redis:
    host: vm.com
    port: 6389
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
          # 转发规则 http://Gateway_HOST:Gateway_PORT/serviceId/**(path)

      routes:
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**

        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/user/**

        - id: mall-apigmallcom
          uri: lb://mall-user
          predicates:
            - Host=api.gmall.com

        - id: mall-item
          uri: lb://mall-web
          predicates:
            - Host=item.gmall.com, passport.gmall.com, order.gmall.com, cart.gmall.com

        - id: mall-index
          uri: lb://mall-web
          predicates:
            - Host=www.gmall.com

        - id: mall-search
          uri: lb://mall-web
          predicates:
            - Host=search.gmall.com
server:
  port: 80

filter:
  whiteList: "myOrder.html" #, cart.html