#spring:
#  profiles:
#    active: dev
spring:
  application:
    name: mall-gateway
  redis:
    host: vm.com
    port: 6389
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
          # 转发规则 http://Gateway_HOST:Gateway_PORT/serviceId/**(path)

      routes:
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**

        - id: mall-item
          uri: lb://mall-web
          predicates:
            - Host=item.mall.com

        - id: mall-index
          uri: lb://mall-web
          predicates:
            - Host=www.mall.com

        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com
server:
  port: 80