server:
  port: 8005

spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
  redis:
    host: vm.com
    port: 6389
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
