server:
  port: 8003

spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
  redis:
    host: vm.com
    port: 6389
    database: 0
    timeout: 180000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        connectTimout: 1000


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/arui/mall/cart/mapper/xml/*.xml