server:
  port: 8006

spring:
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: vm.com
    port: 6389
  rabbitmq:
    host: vm.com
    port: 5672
    username: guest
    password: guest
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cancel:
  order:
    delay: 30000 # 30s