server:
  port: 8200

mybatis-plus:
  mapper-locations: classpath:com/arui/mall/product/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
  rabbitmq:
    virtual-host: vm.com
    port: 5672
    username: guest
    password: guest
  redis:
    host: vm.com
    port: 6389
    database: 0
    timeout: 1800000

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

fastdfs:
  prefix: http://vm.com/