server:
  port: 8002

spring:
  application:
    name: mall-user
  cloud:
    nacos:
      discovery:
        server-addr: vm.com:8848
  redis:
    host: vm.com
    port: 6389
    database: 0
    timeout: 1800000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/arui/mall/user/mapper/xml/*.xml
